[package]

name = "evofighters_rust"
version = "0.0.1"
authors = [ "Josh Kuhn <deontologician@gmail.com>" ]

[dependencies]
time = "0.1.32"
rustc-serialize = "0.3"
rand = "0.4"
enum_primitive = "0.1.1"
num = "0.1.41"

[profile.release]
debug = false
opt-level = 3
rpath = false
lto = true

[[bin]]

name = "evofighters"
