[package]

name = "evofighters_rust"
version = "0.0.1"
authors = [ "Josh Kuhn <deontologician@gmail.com>" ]

[dependencies]

time = "0.1.16"
rustc-serialize = "0.2.12"

[profile.release]
debug = false
opt-level = 3
rpath = false
lto = true

[[bin]]

name = "evofighters"
