[package]

name = "evofighters_rust"
version = "0.0.1"
authors = [ "Josh Kuhn <deontologician@gmail.com>" ]

[dependencies]

time = "0.1.15"
rustc-serialize = "0.2.11"

[profile.release]
debug = true
opt-level = 3
rpath = false
lto = true

[[bin]]

name = "main"
